### ISSUE TITLE
Unable to import required dependencies numpy

### ISSUE THREAD

**Issue by nechry** [madchap/energiapro_gas_consumption#11] opened 2023-10-31 20:50 UTC
Hello, I have been using your appdaemon for a while successfully, but after updating HA to 2023.10.x I was not able to get results like before. The required dependencies are defined correctly.

The error is:

```
2023-10-31 21:40:22.685169 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/energiapro_gas_consumption/apps/energiapro_gas_consumption/energiapro_gas.py
2023-10-31 21:40:22.701089 WARNING Error: ------------------------------------------------------------
2023-10-31 21:40:22.701267 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/energiapro_gas_consumption/apps/energiapro_gas_consumption/energiapro_gas.py:
2023-10-31 21:40:22.701548 WARNING Error: ------------------------------------------------------------
2023-10-31 21:40:22.704020 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/energiapro_gas_consumption/apps/energiapro_gas_consumption/energiapro_gas.py", line 3, in <module>
    import pandas as pd
  File "/usr/lib/python3.11/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

2023-10-31 21:40:22.704195 WARNING Error: ------------------------------------------------------------
2023-10-31 21:40:22.704306 WARNING AppDaemon: Removing associated apps:
2023-10-31 21:40:22.704421 WARNING AppDaemon: energiapro_gas_consumption
```

My HA setup is a VMware based on the official image.

thank you in advance for your help

**Comment by madchap** [comment] 2023-11-08 06:47
Thanks for the report. It seems other things broke and since I had lorawan connection issues, I was misled in thinking the problem was there and not with my code.

I'll look into this.

**Comment by madchap** [comment] 2023-11-19 11:28
Hi @nechry 

As I was trying to find a workaround against newest EnergiaPro's security measure, I could not reproduce your issue.

Please take a look at the README, as I just introduced a new way to get the data. This is a breaking change, unfortunately.

Cheers.
fred

**Comment by madchap** [comment] 2023-11-19 16:34
Closing, as it's unrelated to the energiapro appdaemon code.

**Closed as completed by madchap** 2023-11-19 16:34 UTC

**Comment by nechry** [comment] 2023-11-22 14:13
I'm waiting to have access to the API. merci
